### PR TITLE
feat: introduce layouts

### LINKED ISSUE #32: add layout system from vitesse.

### PR DESCRIPTION
**Pull request by portlek**
app.vue removed, layout system added.
comes from [vitesse](https://github.com/antfu/vitesse)
followed the [guide](https://v3.nuxtjs.org/guide/directory-structure/layouts/)
closes #32

### CODE REVIEW

**Comment by Atinux** [comment]
I don't think it is a good idea to remove `app.vue`

**Comment by Atinux** [comment]
I would like to also have @danielroe opinion on this regarding the 404 error best practices.

**Comment by portlek** [comment]
if i don't remove app.vue, layout system does not work at all, at least i couldn't do it with app.vue.

**Comment by Atinux** [comment]
You should be able to use Layouts with app.vue right @danielroe ?

**Comment by portlek** [comment]
i guess i found the way.

**Pull request merged**
