### PR TITLE
fix: toggleDark not works

### PR DESCRIPTION
**Pull request by YunYouJun**
### Description

https://vitesse-nuxt3.netlify.app/

Just click the toggle button in demo, it doesn't work.

I test `color.value` can fix it.

### CODE REVIEW

**Comment by sibbng** [comment]
Source of problem is outdated @nuxt/kit version in @nuxtjs/color-mode: https://github.com/nuxt-modules/color-mode/issues/175

Failed auto-import registration caused this import to be taken from @vueuse/nuxt module. This change causes flash on full reload and should be reverted when https://github.com/nuxt-modules/color-mode/issues/175 is fixed.

I temporarily fixed the flash issue by adding these lines on package.json

```
"pnpm": {
  "overrides": {
    "@nuxt/kit": "^3.0.0"
  }
}
```

**Comment by YunYouJun** [comment]
The current approach uses `useColorMode` directly from `@vueuse`.
Is there any theoretical difference between vueuse `useColorMode` and nuxt `useColorMode`?
I didn't go into it, maybe you can create a PR to fix it temporarily.

---

But is it possible for us to make vueuse's `useColorMode` more consistent with nuxt's `useColorMode`?

**Comment by sibbng** [comment]
It seems https://github.com/nuxt-modules/color-mode/issues/175 is fixed in v3.2.0. @YunYouJun Could you make a PR to revert this change? (there should be revert button next to merge message)

**Comment by YunYouJun** [comment]
@sibbng I create a new PR to fix it. https://github.com/antfu/vitesse-nuxt3/pull/69
Because we also need to upgrade `@nuxtjs/color-mode`.

**Pull request merged**
